services:
  - type: web
    name: cyberrecon-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SCAN_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://cyberrecon.vercel.app
      - key: TASK_QUEUE_MODE
        value: inprocess
      - key: NMAP_PATH
        value: nmap
